echo "               AAA                                                                                                                                            "
echo "              A:::A                                                                                                                                           "
echo "             A:::::A                                                                                                                                          "
echo "            A:::::::A                                                                                                                                         "
echo "           A:::::::::Awwwwwww           wwwww           wwwwwww eeeeeeeeeeee        ssssssssss      ooooooooooo      mmmmmmm    mmmmmmm       eeeeeeeeeeee    "
echo "          A:::::A:::::Aw:::::w         w:::::w         w:::::wee::::::::::::ee    ss::::::::::s   oo:::::::::::oo  mm:::::::m  m:::::::mm   ee::::::::::::ee  "
echo "         A:::::A A:::::Aw:::::w       w:::::::w       w:::::we::::::eeeee:::::eess:::::::::::::s o:::::::::::::::om::::::::::mm::::::::::m e::::::eeeee:::::ee"
echo "        A:::::A   A:::::Aw:::::w     w:::::::::w     w:::::we::::::e     e:::::es::::::ssss:::::so:::::ooooo:::::om::::::::::::::::::::::me::::::e     e:::::e"
echo "       A:::::A     A:::::Aw:::::w   w:::::w:::::w   w:::::w e:::::::eeeee::::::e s:::::s  ssssss o::::o     o::::om:::::mmm::::::mmm:::::me:::::::eeeee::::::e"
echo "      A:::::AAAAAAAAA:::::Aw:::::w w:::::w w:::::w w:::::w  e:::::::::::::::::e    s::::::s      o::::o     o::::om::::m   m::::m   m::::me:::::::::::::::::e "
echo "     A:::::::::::::::::::::Aw:::::w:::::w   w:::::w:::::w   e::::::eeeeeeeeeee        s::::::s   o::::o     o::::om::::m   m::::m   m::::me::::::eeeeeeeeeee  "
echo "    A:::::AAAAAAAAAAAAA:::::Aw:::::::::w     w:::::::::w    e:::::::e           ssssss   s:::::s o::::o     o::::om::::m   m::::m   m::::me:::::::e           "
echo "   A:::::A             A:::::Aw:::::::w       w:::::::w     e::::::::e          s:::::ssss::::::so:::::ooooo:::::om::::m   m::::m   m::::me::::::::e          "
echo "  A:::::A               A:::::Aw:::::w         w:::::w       e::::::::eeeeeeee  s::::::::::::::s o:::::::::::::::om::::m   m::::m   m::::m e::::::::eeeeeeee  "
echo " A:::::A                 A:::::Aw:::w           w:::w         ee:::::::::::::e   s:::::::::::ss   oo:::::::::::oo m::::m   m::::m   m::::m  ee:::::::::::::e  "
echo "AAAAAAA                   AAAAAAAwww             www            eeeeeeeeeeeeee    sssssssssss       ooooooooooo   mmmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee  "